import {scanDocuments, checkHealth, exportExcel} from './api.js';
const $ = id => document.getElementById(id); let selectedFiles=[], records=[], filter='all', editing=-1;
const editableFields=['tc_no','name','surname','birth_date','serial_no','expiry_date','gender','nationality','mother_name','father_name','issuing_authority'];
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),3500)}
async function health(){try{const data=await checkHealth();$('health').textContent=data.ocr_ready?'● Sistem hazır':'○ OCR sistemi hazırlanıyor…';$('health').classList.toggle('ready',data.ocr_ready);$('scanBtn').disabled=!data.ocr_ready;if(!data.ocr_ready)setTimeout(health,3000)}catch{ $('health').textContent='● Sunucuya ulaşılamıyor';setTimeout(health,5000)}} health();
function pick(files){selectedFiles=Array.from(files||[]);if(!selectedFiles.length)return;const total=selectedFiles.reduce((sum,file)=>sum+file.size,0);$('fileInfo').innerHTML=`<strong>${selectedFiles.length} dosya seçildi</strong><span>${(total/1024/1024).toFixed(1)} MB</span><small>${selectedFiles.map(file=>esc(file.name)).join(' • ')}</small>`;$('fileInfo').classList.remove('hidden');$('scanBtn').classList.remove('hidden')}
$('chooseBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>pick(e.target.files);
['dragenter','dragover'].forEach(x=>$('dropZone').addEventListener(x,e=>{e.preventDefault();$('dropZone').classList.add('over')}));['dragleave','drop'].forEach(x=>$('dropZone').addEventListener(x,e=>{e.preventDefault();$('dropZone').classList.remove('over')}));$('dropZone').ondrop=e=>pick(e.dataTransfer.files);
$('scanBtn').onclick=async()=>{if(!selectedFiles.length)return;$('uploadView').classList.add('hidden');$('loadingView').classList.remove('hidden');try{const data=await scanDocuments(selectedFiles);records=data.documents;showResults()}catch(e){toast(e.message);$('uploadView').classList.remove('hidden')}finally{$('loadingView').classList.add('hidden')}};
function status(r){return r.failed?'failed':r.requires_review?'review':'success'} function mask(tc){return tc?`${'*'.repeat(Math.max(0,tc.length-2))}${tc.slice(-2)}`:'-----------'}
function showResults(){$('resultView').classList.remove('hidden');render()}
function render(){const counts={success:0,review:0,failed:0};records.forEach(r=>counts[status(r)]++);$('summary').innerHTML=`<article><b>${records.length}</b><span>Toplam belge</span></article><article><b>${counts.success}</b><span>Başarılı</span></article><article><b>${counts.review}</b><span>Kontrol gerekli</span></article><article><b>${counts.failed}</b><span>Okunamadı</span></article>`;
 const visible=records.map((r,i)=>[r,i]).filter(([r])=>filter==='all'||status(r)===filter);$('rows').innerHTML=visible.map(([r,i])=>`<tr data-i="${i}"><td>${r.document}${r.page>1?` / ${r.page}`:''}</td><td class="mono">${mask(r.tc_no.value)}</td><td>${esc(r.name.value)||'—'}</td><td>${esc(r.surname.value)||'—'}</td><td>${esc(r.birth_date.value)||'—'}</td><td class="mono">${esc(r.serial_no.value)||'—'}</td><td>${esc(r.expiry_date.value)||'—'}</td><td>${esc(r.gender.value)||'—'}</td><td>${esc(r.nationality.value)||'—'}</td><td>${esc(r.mother_name.value)||'—'}</td><td>${esc(r.father_name.value)||'—'}</td><td>${esc(r.issuing_authority.value)||'—'}</td><td>%${Math.round(r.overall_confidence*100)}</td><td><span class="pill ${status(r)}">${r.failed?'Okunamadı':r.requires_review?'Kontrol':'Başarılı'}</span></td></tr>`).join('');document.querySelectorAll('#rows tr').forEach(row=>row.onclick=()=>openEdit(+row.dataset.i))}
document.querySelectorAll('#filters button').forEach(btn=>btn.onclick=()=>{filter=btn.dataset.filter;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x===btn));render()});$('reviewOnly').onclick=()=>{filter='review';document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x.dataset.filter==='review'));render()};
function openEdit(i){editing=i;const r=records[i],form=$('editDialog').querySelector('form');editableFields.forEach(k=>form.elements[k].value=r[k]?.value||'');form.elements.confidence.value=`%${Math.round(r.overall_confidence*100)}`;$('errors').textContent=r.errors?.join(' ')||'';$('editDialog').showModal()}
$('saveEdit').onclick=e=>{e.preventDefault();const r=records[editing],form=$('editDialog').querySelector('form');editableFields.forEach(k=>{r[k]??={};r[k].value=form.elements[k].value.trim();r[k].valid=!!r[k].value});r.failed=false;r.requires_review=false;r.errors=[];$('editDialog').close();render();toast('Değişiklikler tarayıcı belleğinde uygulandı.')};
$('newScan').onclick=()=>location.reload();$('exportBtn').onclick=async()=>{const review=records.filter(r=>r.requires_review||r.failed).length;if(review&&!confirm(`${review} kayıt henüz kontrol edilmedi. Yine de Excel oluşturmak istiyor musunuz?`))return;try{await exportExcel(records.map(r=>Object.assign({document:r.document,page:r.page,confidence:r.overall_confidence,requires_review:r.requires_review||r.failed},Object.fromEntries(editableFields.map(k=>[k,r[k]?.value||''])))))}catch(e){toast(e.message)}};
